id: DBD8D5BCC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:50:07+00:00'
last_modified: '2022-05-27T16:01:10.807248+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4958':
      image_group_id: I1PD95910
      title: ཚིགས་སུ་བཅད་པ་གཅིག་པའི་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: 4958.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
