id: PD72B81D1
initial_creation_type: ocr
source_metadata:
  volumes:
    dee93061ba654c5398e02d13249c7383:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ཚིགས་སུ་བཅད་པ་གཅིག་པའི་བཤད་པ།
      total_pages: 1498
      volume_number: 65
